
- name: Extract major and minor version
  set_fact:
    version_short: "{{ ansible_distribution_version.split('.')[:2] | join('.') }}"

- name: ensure users exist with the right config
  include_tasks: user.yaml  
  loop: "{{ common_users | dict2items(key_name='user', value_name='config') }}"

- name: ensure doas configuration is gud
  copy:
    src: ../../files/doas.conf
    dest: /etc/doas.conf
    mode: '0644'
    owner: root
    group: root

- name: ensure community repository is enabled
  lineinfile:
    line: "http://dl-cdn.alpinelinux.org/alpine/v{{ version_short }}/community"
    path: /etc/apk/repositories

- name: update and upgrade apk
  apk:
    update_cache: yes
    upgrade: yes

- name: apk add packages
  apk:
    name: "{{ alpinePackages }}"
