
# CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
# CLI_ARCH=amd64
# if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
# curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
# sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
# sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
# rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}

- name: "set correct arch"
  set_fact:
    parsed_architecture: "{{ [ansible_architecture] | map('extract', arch_map) | first }}"
  vars:
    arch_map:
      aarch64: "arm64"
      x86_64: "amd64"

- name: "download cilium cli"
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ k3s_cli_cilium_version }}/cilium-linux-{{ parsed_architecture }}.tar.gz"
    checksum: "sha256:https://github.com/cilium/cilium-cli/releases/download/{{ k3s_cli_cilium_version }}/cilium-linux-{{ parsed_architecture }}.tar.gz.sha256sum"
    dest: /tmp/cilium-linux.tar.gz

- name: "unarchive & move cilium cli"
  unarchive:
    remote_src: true
    src: /tmp/cilium-linux.tar.gz
    dest: /usr/local/bin

- name: "install Cilium"
  run_once: true
  command: "cilium install --version={{ k3s_cilium_version }} --set=ipam.operator.clusterPoolIPv4PodCIDRList='10.42.0.0/16'"
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: "wait for Cilium status to be okay"
  run_once: true
  shell: "cilium status"
  register: "cilium_status"
  until: "cilium_status is not failed"
  delay: 60