
- name: configure nodes
  hosts: home_k3s
  become: yes
  vars_files:
  - vars/main.yaml
  - vars/vault.yaml
  roles:
  - name: k86td.common
    tags: common
  - name: k86td.k3s
    tags: k3s
  tasks:
  - delegate_to: "{{ groups.server[0] }}"
    run_once: true
    block:
    - name: "install ArgoCD manifest in /tmp"
      get_url:
        url: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
        dest: "/tmp/argocd-stable.yaml"

    - name: "create ArgoCD namespace"
      command: "kubectl create namespace argocd"

    - name: "apply ArgoCD manifest"
      command: "kubectl apply -n argocd -f /tmp/argocd-stable.yaml"

