
- name: configure nodes
  hosts: home_k3s
  become: yes
  vars_files:
  - vars/main.yaml
  - vars/vault.yaml
  roles:
  - name: k86td.common
    tags: common
  - name: k86td.k3s
    tags: k3s
  tasks:
  - run_once: true
    delegate_to: "127.0.0.1"
    block:
    - name: "create ArgoCD namespace"
      kubernetes.core.k8s:
        kubeconfig: artifacts/kubeconfig.yaml
        apply: true
        api_version: "v1"
        kind: "Namespace"
        name: "argocd"

    - name: "install ArgoCD manifest"
      kubernetes.core.k8s:
        kubeconfig: artifacts/kubeconfig.yaml
        apply: true
        namespace: argocd
        src: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"

